#!/bin/bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE_PATH="$1"
IP_ADDRESS="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME"@"$IP_ADDRESS":~/ || { echo "Error transferring file."; exit 1; }

echo "$FILE_PATH transferred successfully to $USERNAME@$IP_ADDRESS:~/"

